# Generated by Django 5.0.2 on 2024-04-02 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroday', '0003_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conclusion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
